export const PROTOCOL_VERSION = "0.1.0";

export const REMOTE_COMMAND_TYPES = [
  "bind_session",
  "send_message",
  "interrupt_turn",
  "get_status",
  "list_sessions",
  "load_history",
  "get_sidebar",
  "task_create_after",
  "task_create_at",
  "task_create_daily",
  "task_create_every",
  "task_delete",
  "task_enable",
  "task_disable",
  "task_update_instruction",
  "task_reschedule_after",
  "task_reschedule_at",
  "task_reschedule_daily",
  "task_reschedule_every",
  "skill_install",
  "skill_uninstall",
  "mcp_create",
  "mcp_update",
  "mcp_delete",
  "mcp_enable",
  "mcp_disable",
  "clear_remote_runtime",
] as const;

export const REMOTE_EVENT_TYPES = [
  "ready",
  "session_bound",
  "turn_started",
  "progress",
  "delta",
  "stream_end",
  "message",
  "turn_completed",
  "interrupt_result",
  "status_result",
  "history_snapshot",
  "session_list",
  "task_delivered",
  "sidebar_snapshot",
  "resource_action_result",
  "error",
] as const;
